- name: Create ssh command configuration
  template:
    src: ssh_proxy_command.j2
    dest: "/etc/acng-ssh-proxy/{{ ansible_hostname }}"
    owner: root
    group: nagios
    mode: "0654"
  delegate_to: "{{ acng_server }}"

- name: Enable and start service
  systemd:
    daemon-reload: yes
    name: "acng_ssh_proxy@{{ ansible_hostname }}"
    enabled: yes
    state: started
  delegate_to: "{{ acng_server }}"
